name: 1st-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
#   schedule:
#     - cron: '*/5 * * * *'
  push:
    branches:
      - main

  workflow_dispatch:


# jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: echo test...
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444
          - 7900:7900
        options: --shm-size="2g"

    steps:
      - uses: actions/checkout@v3
      # - name: Get IP Address
      #   run: echo "##[set-output name=ip;]$(ifconfig eth0 | grep 'inet [0-9\.]* ' -o | sed 's/[^0-9\.]//g')"
      #   id: ip_addr 
      
      - name: Setup Pyhon
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: change working directory
        run: |
          cd py_test_script
          pwd
          ls -l

      - name: Install Python dependencies
        run: |
          pwd
          cd py_test_script
          pwd
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          cd py_test_script
          python3 ./t001.py
          # python3 -m pytest -v --html=report.html --self-contained-html
          # python3 -m pytest -v --junitxml=report.xml
          # python3 -m pytest -v --alluredir=allure-results
          # allure generate allure-results --clean -o allure-report
          # allure open allure-report

